language: node_js

node_js:
  - "11.9.0"

cache:
  yarn: true

stages:
  - lint
  - test

jobs:
  include:

    - stage: lint
      script:
        - yarn build
        - yarn lint

    - stage: test
      script:
        - yarn build
        - yarn test
