language: node_js

cache:
  yarn: true

stages:
  - lint
  - test

jobs:
  include:

    - stage: lint
      script:
        - yarn build
        - yarn lint

    - stage: test
      script:
        - yarn build
        - yarn test
